# Use the official KrakenD image
FROM krakend:2.9

# Copy your gateway config into the container
COPY krakend.json /etc/krakend/krakend.json

# Expose the port KrakenD will listen on
EXPOSE 8081

# Launch KrakenD with that config
CMD ["krakend", "run", "-c", "/etc/krakend/krakend.json"]
