apiVersion: v1
kind: Service
metadata:
  name: user-gateway
  namespace: userdomain
spec:
  type: LoadBalancer
  selector:
    app: user-gateway
  ports:
    - port: 81
      targetPort: 8081
      protocol: TCP
      name: http
