apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-gateway
  namespace: userdomain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-gateway
  template:
    metadata:
      labels:
        app: user-gateway
    spec:
      containers:
      - name: user-gateway
        image: krakend:2.9
        args: ["run", "-c", "/etc/krakend/krakend.json"]
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: krakend-config
          mountPath: /etc/krakend/krakend.json
          subPath: krakend.json
      volumes:
      - name: krakend-config
        configMap:
          name: krakend-config
