apiVersion: v1
kind: Service
metadata:
  name: festival-service-api
  namespace: festivaldomain
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: festival-service-api