apiVersion: v1
kind: Service
metadata:
  name: festival-gateway
  namespace: festivaldomain
spec:
  type: LoadBalancer
  selector:
    app: festival-gateway
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
